// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MvcMusicStore.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PaimentDesItemsDuPanierFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Commandes.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("fr-CA"), "Paiment des items du panier", "En tant que client, je veux payer les items dans mon panier.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Paiment des items du panier")))
            {
                MvcMusicStore.Tests.PaimentDesItemsDuPanierFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line 5
 testRunner.Given("que je suis un client authentifié", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Étant donné ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Saisir les informations pour le paiement et confirmer l\'achat")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Paiment des items du panier")]
        public virtual void SaisirLesInformationsPourLePaiementEtConfirmerLAchat()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Saisir les informations pour le paiement et confirmer l\'achat", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line 9
 testRunner.Given("que je suis sur la page du panier d\'achat", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Étant donné ");
#line 10
 testRunner.When("je clique sur lien Commander", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Champ",
                        "Valeur"});
            table1.AddRow(new string[] {
                        "Prénom",
                        "Joe"});
            table1.AddRow(new string[] {
                        "Nom",
                        "Légumineuse"});
            table1.AddRow(new string[] {
                        "Adresse",
                        "1234 rue Fictive"});
            table1.AddRow(new string[] {
                        "Ville",
                        "Ivujiivik"});
            table1.AddRow(new string[] {
                        "Province",
                        "Québec"});
            table1.AddRow(new string[] {
                        "Code postal",
                        "G1Q 1Q9"});
            table1.AddRow(new string[] {
                        "Pays",
                        "Canada"});
            table1.AddRow(new string[] {
                        "Téléphone",
                        "418-555-1234"});
            table1.AddRow(new string[] {
                        "Courriel",
                        "joelegumineuse@brocoli.com"});
            table1.AddRow(new string[] {
                        "Code Promo",
                        "FREE"});
#line 11
 testRunner.And("que je saisi les informations suivantes", ((string)(null)), table1, "Et ");
#line 23
 testRunner.And("que je soumet le formulaire", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line 24
 testRunner.Then("mon paiment est complété avec succès", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
